version: "3.9"  # optional since v1.27.0

services:

  app_web_planetas_star_wars:
    restart: unless-stopped
    build: .
    hostname: app-web_planeta_star_wars
    ports:
      - "9999:8080"
    volumes:
      - .:/code
      - logvolume:/var/log
    depends_on:
      - db_planetas_star_wars
    links:
      - db_planetas_star_wars
    environment:
      HOST: db
      BANCO: ${NOME_BANCO}
      USUARIO: ${USUARIO_BANCO}
      SENHA: ${SENHA_BANCO_USER}
## Usado pelo Falyway para inicializaçao e atualização da App.
      USUARIO_ROOT_APP: ${USUARIO_ROOT_APP}
      SENHA_ROOT_APP: ${SENHA_ROOT_APP}
    networks:
      - frontend
      - backend

  db_planetas_star_wars:
    image: mariadb:10.3.29
    restart: on-failure
    hostname: db
    environment:
      MYSQL_DATABASE: ${NOME_BANCO}
      MARIADB_ROOT_PASSWORD: ${SENHA_ROOT_APP}
      MARIADB_USER: ${USUARIO_BANCO}
      MARIADB_PASSWORD: ${SENHA_BANCO_USER}
      MYSQL_INITDB_SKIP_TZINFO: 1
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      - backend

volumes:
  mysql-db: {}
  logvolume: {}

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge